
// This file has been generated by the GUI designer. Do not modify.
namespace R7.Webmaster.Addins.PasswordGenerator
{
	public partial class PasswordGeneratorWidget
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action actionGenerate;
		
		private global::Gtk.Action actionGuid;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.CheckButton checkAllowRepeated;
		
		private global::Gtk.CheckButton checkIncludeCustom;
		
		private global::Gtk.CheckButton checkIncludeDigits;
		
		private global::Gtk.CheckButton checkIncludeLowercase;
		
		private global::Gtk.CheckButton checkIncludeSpecialChars;
		
		private global::Gtk.CheckButton checkIncludeUnderscore;
		
		private global::Gtk.CheckButton checkIncludeUppercase;
		
		private global::Gtk.CheckButton checkInsertSeparator;
		
		private global::Gtk.Entry entry1;
		
		private global::Gtk.Entry entryCustomChars;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.SpinButton spinbutton1;
		
		private global::Gtk.SpinButton spinNPasswords;
		
		private global::Gtk.Expander expander1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView textview1;
		
		private global::Gtk.Label GtkLabel10;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget R7.Webmaster.Addins.PasswordGenerator.PasswordGeneratorWidget
			Stetic.BinContainer w1 = global::Stetic.BinContainer.Attach (this);
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup ("Default");
			this.actionGenerate = new global::Gtk.Action ("actionGenerate", global::Mono.Unix.Catalog.GetString ("_Passwords"), null, "gtk-media-play");
			this.actionGenerate.IsImportant = true;
			this.actionGenerate.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Passwords");
			w2.Add (this.actionGenerate, null);
			this.actionGuid = new global::Gtk.Action ("actionGuid", global::Mono.Unix.Catalog.GetString ("GUIDs"), null, "gtk-media-play");
			this.actionGuid.IsImportant = true;
			this.actionGuid.ShortLabel = global::Mono.Unix.Catalog.GetString ("GUIDs");
			w2.Add (this.actionGuid, null);
			this.UIManager.InsertActionGroup (w2, 0);
			this.Name = "R7.Webmaster.Addins.PasswordGenerator.PasswordGeneratorWidget";
			// Container child R7.Webmaster.Addins.PasswordGenerator.PasswordGeneratorWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(6)), ((uint)(5)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.table1.BorderWidth = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.checkAllowRepeated = new global::Gtk.CheckButton ();
			this.checkAllowRepeated.CanFocus = true;
			this.checkAllowRepeated.Name = "checkAllowRepeated";
			this.checkAllowRepeated.Label = global::Mono.Unix.Catalog.GetString ("Allow repeated chars");
			this.checkAllowRepeated.Active = true;
			this.checkAllowRepeated.DrawIndicator = true;
			this.checkAllowRepeated.UseUnderline = true;
			this.table1.Add (this.checkAllowRepeated);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkAllowRepeated]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.LeftAttach = ((uint)(3));
			w3.RightAttach = ((uint)(4));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.checkIncludeCustom = new global::Gtk.CheckButton ();
			this.checkIncludeCustom.CanFocus = true;
			this.checkIncludeCustom.Name = "checkIncludeCustom";
			this.checkIncludeCustom.Label = global::Mono.Unix.Catalog.GetString ("Include custom:");
			this.checkIncludeCustom.DrawIndicator = true;
			this.checkIncludeCustom.UseUnderline = true;
			this.table1.Add (this.checkIncludeCustom);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkIncludeCustom]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(2));
			w4.RightAttach = ((uint)(3));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table1.Gtk.Table+TableChild
			this.checkIncludeDigits = new global::Gtk.CheckButton ();
			this.checkIncludeDigits.CanFocus = true;
			this.checkIncludeDigits.Name = "checkIncludeDigits";
			this.checkIncludeDigits.Label = global::Mono.Unix.Catalog.GetString ("Include digits");
			this.checkIncludeDigits.Active = true;
			this.checkIncludeDigits.DrawIndicator = true;
			this.checkIncludeDigits.UseUnderline = true;
			this.table1.Add (this.checkIncludeDigits);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkIncludeDigits]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.LeftAttach = ((uint)(3));
			w5.RightAttach = ((uint)(4));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.checkIncludeLowercase = new global::Gtk.CheckButton ();
			this.checkIncludeLowercase.CanFocus = true;
			this.checkIncludeLowercase.Name = "checkIncludeLowercase";
			this.checkIncludeLowercase.Label = global::Mono.Unix.Catalog.GetString ("Include lowercase");
			this.checkIncludeLowercase.Active = true;
			this.checkIncludeLowercase.DrawIndicator = true;
			this.checkIncludeLowercase.UseUnderline = true;
			this.table1.Add (this.checkIncludeLowercase);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkIncludeLowercase]));
			w6.LeftAttach = ((uint)(4));
			w6.RightAttach = ((uint)(5));
			w6.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table1.Gtk.Table+TableChild
			this.checkIncludeSpecialChars = new global::Gtk.CheckButton ();
			this.checkIncludeSpecialChars.CanFocus = true;
			this.checkIncludeSpecialChars.Name = "checkIncludeSpecialChars";
			this.checkIncludeSpecialChars.Label = global::Mono.Unix.Catalog.GetString ("Include special chars");
			this.checkIncludeSpecialChars.DrawIndicator = true;
			this.checkIncludeSpecialChars.UseUnderline = true;
			this.table1.Add (this.checkIncludeSpecialChars);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkIncludeSpecialChars]));
			w7.LeftAttach = ((uint)(2));
			w7.RightAttach = ((uint)(3));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.checkIncludeUnderscore = new global::Gtk.CheckButton ();
			this.checkIncludeUnderscore.CanFocus = true;
			this.checkIncludeUnderscore.Name = "checkIncludeUnderscore";
			this.checkIncludeUnderscore.Label = global::Mono.Unix.Catalog.GetString ("Include \"__\"");
			this.checkIncludeUnderscore.Active = true;
			this.checkIncludeUnderscore.DrawIndicator = true;
			this.checkIncludeUnderscore.UseUnderline = true;
			this.table1.Add (this.checkIncludeUnderscore);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkIncludeUnderscore]));
			w8.LeftAttach = ((uint)(3));
			w8.RightAttach = ((uint)(4));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.checkIncludeUppercase = new global::Gtk.CheckButton ();
			this.checkIncludeUppercase.CanFocus = true;
			this.checkIncludeUppercase.Name = "checkIncludeUppercase";
			this.checkIncludeUppercase.Label = global::Mono.Unix.Catalog.GetString ("Include uppercase");
			this.checkIncludeUppercase.Active = true;
			this.checkIncludeUppercase.DrawIndicator = true;
			this.checkIncludeUppercase.UseUnderline = true;
			this.table1.Add (this.checkIncludeUppercase);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkIncludeUppercase]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.LeftAttach = ((uint)(4));
			w9.RightAttach = ((uint)(5));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.checkInsertSeparator = new global::Gtk.CheckButton ();
			this.checkInsertSeparator.CanFocus = true;
			this.checkInsertSeparator.Name = "checkInsertSeparator";
			this.checkInsertSeparator.Label = global::Mono.Unix.Catalog.GetString ("Separate blocks");
			this.checkInsertSeparator.Active = true;
			this.checkInsertSeparator.DrawIndicator = true;
			this.checkInsertSeparator.UseUnderline = true;
			this.table1.Add (this.checkInsertSeparator);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkInsertSeparator]));
			w10.TopAttach = ((uint)(4));
			w10.BottomAttach = ((uint)(5));
			w10.LeftAttach = ((uint)(2));
			w10.RightAttach = ((uint)(3));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry1 = new global::Gtk.Entry ();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '●';
			this.table1.Add (this.entry1);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry1]));
			w11.TopAttach = ((uint)(5));
			w11.BottomAttach = ((uint)(6));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(5));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryCustomChars = new global::Gtk.Entry ();
			this.entryCustomChars.Sensitive = false;
			this.entryCustomChars.CanFocus = true;
			this.entryCustomChars.Name = "entryCustomChars";
			this.entryCustomChars.IsEditable = true;
			this.entryCustomChars.InvisibleChar = '●';
			this.table1.Add (this.entryCustomChars);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryCustomChars]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.LeftAttach = ((uint)(2));
			w12.RightAttach = ((uint)(3));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.table1.Add (this.hseparator1);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.hseparator1]));
			w13.TopAttach = ((uint)(3));
			w13.BottomAttach = ((uint)(4));
			w13.RightAttach = ((uint)(5));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 1F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Password length:");
			this.table1.Add (this.label1);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.label1]));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 1F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Last entry:");
			this.table1.Add (this.label2);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
			w15.TopAttach = ((uint)(5));
			w15.BottomAttach = ((uint)(6));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 1F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Block size:");
			this.table1.Add (this.label3);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.label3]));
			w16.TopAttach = ((uint)(4));
			w16.BottomAttach = ((uint)(5));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.spinbutton1 = new global::Gtk.SpinButton (1, 100, 1);
			this.spinbutton1.CanFocus = true;
			this.spinbutton1.Name = "spinbutton1";
			this.spinbutton1.Adjustment.PageIncrement = 10;
			this.spinbutton1.ClimbRate = 1;
			this.spinbutton1.Numeric = true;
			this.spinbutton1.Value = 8;
			this.table1.Add (this.spinbutton1);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1 [this.spinbutton1]));
			w17.LeftAttach = ((uint)(1));
			w17.RightAttach = ((uint)(2));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.spinNPasswords = new global::Gtk.SpinButton (1, 100, 1);
			this.spinNPasswords.CanFocus = true;
			this.spinNPasswords.Name = "spinNPasswords";
			this.spinNPasswords.Adjustment.PageIncrement = 10;
			this.spinNPasswords.ClimbRate = 1;
			this.spinNPasswords.Numeric = true;
			this.spinNPasswords.SnapToTicks = true;
			this.spinNPasswords.Value = 1;
			this.table1.Add (this.spinNPasswords);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1 [this.spinNPasswords]));
			w18.TopAttach = ((uint)(4));
			w18.BottomAttach = ((uint)(5));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add (this.table1);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table1]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.expander1 = new global::Gtk.Expander (null);
			this.expander1.CanFocus = true;
			this.expander1.Name = "expander1";
			this.expander1.Expanded = true;
			this.expander1.BorderWidth = ((uint)(6));
			// Container child expander1.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview1 = new global::Gtk.TextView ();
			this.textview1.HeightRequest = 200;
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.textview1.WrapMode = ((global::Gtk.WrapMode)(1));
			this.GtkScrolledWindow.Add (this.textview1);
			this.expander1.Add (this.GtkScrolledWindow);
			this.GtkLabel10 = new global::Gtk.Label ();
			this.GtkLabel10.Name = "GtkLabel10";
			this.GtkLabel10.LabelProp = global::Mono.Unix.Catalog.GetString ("History:");
			this.GtkLabel10.UseUnderline = true;
			this.expander1.LabelWidget = this.GtkLabel10;
			this.vbox1.Add (this.expander1);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.expander1]));
			w22.PackType = ((global::Gtk.PackType)(1));
			w22.Position = 1;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			w1.SetUiManager (UIManager);
			this.Hide ();
			this.actionGenerate.Activated += new global::System.EventHandler (this.OnActionGenerateActivated);
			this.actionGuid.Activated += new global::System.EventHandler (this.OnActionGuidActivated);
			this.checkIncludeCustom.Toggled += new global::System.EventHandler (this.OnCheckIncludeCustomToggled);
		}
	}
}
