
// This file has been generated by the GUI designer. Do not modify.
namespace R7.Webmaster.Addins.Characters
{
	public partial class CharactersWidget
	{
		private global::Gtk.VBox vbox1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget R7.Webmaster.Addins.Characters.CharactersWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "R7.Webmaster.Addins.Characters.CharactersWidget";
			// Container child R7.Webmaster.Addins.Characters.CharactersWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
