
// This file has been generated by the GUI designer. Do not modify.
namespace R7.Webmaster.Addins.TableCleaner
{
	public partial class TableCleanerWidget
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action actionProcess;
		
		private global::Gtk.ToggleAction toggleAutoCopy;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.TextView txvResult;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.Alignment alignment2;
		
		private global::Gtk.Table tableClearTablesOptions;
		
		private global::Gtk.CheckButton checkSetWidth;
		
		private global::Gtk.ComboBox comboWidthUnits;
		
		private global::Gtk.Entry entryTableClass;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.SpinButton spinTableWidth;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget R7.Webmaster.Addins.TableCleaner.TableCleanerWidget
			Stetic.BinContainer w1 = global::Stetic.BinContainer.Attach (this);
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup ("Default");
			this.actionProcess = new global::Gtk.Action ("actionProcess", global::Mono.Unix.Catalog.GetString ("_Process"), null, "gtk-media-play");
			this.actionProcess.IsImportant = true;
			this.actionProcess.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Process");
			w2.Add (this.actionProcess, null);
			this.toggleAutoCopy = new global::Gtk.ToggleAction ("toggleAutoCopy", global::Mono.Unix.Catalog.GetString ("_Auto Copy"), null, "gtk-copy");
			this.toggleAutoCopy.Active = true;
			this.toggleAutoCopy.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Auto Copy");
			w2.Add (this.toggleAutoCopy, null);
			this.UIManager.InsertActionGroup (w2, 0);
			this.Name = "R7.Webmaster.Addins.TableCleaner.TableCleanerWidget";
			// Container child R7.Webmaster.Addins.TableCleaner.TableCleanerWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.txvResult = new global::Gtk.TextView ();
			this.txvResult.HeightRequest = 100;
			this.txvResult.CanFocus = true;
			this.txvResult.Name = "txvResult";
			this.txvResult.WrapMode = ((global::Gtk.WrapMode)(3));
			this.GtkScrolledWindow1.Add (this.txvResult);
			this.hbox4.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.GtkScrolledWindow1]));
			w4.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(1)), ((uint)(1)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.alignment2.LeftPadding = ((uint)(24));
			this.alignment2.RightPadding = ((uint)(10));
			// Container child alignment2.Gtk.Container+ContainerChild
			this.tableClearTablesOptions = new global::Gtk.Table (((uint)(2)), ((uint)(3)), false);
			this.tableClearTablesOptions.Name = "tableClearTablesOptions";
			this.tableClearTablesOptions.RowSpacing = ((uint)(6));
			this.tableClearTablesOptions.ColumnSpacing = ((uint)(6));
			// Container child tableClearTablesOptions.Gtk.Table+TableChild
			this.checkSetWidth = new global::Gtk.CheckButton ();
			this.checkSetWidth.CanFocus = true;
			this.checkSetWidth.Name = "checkSetWidth";
			this.checkSetWidth.Label = global::Mono.Unix.Catalog.GetString ("Set Width:");
			this.checkSetWidth.DrawIndicator = true;
			this.checkSetWidth.UseUnderline = true;
			this.tableClearTablesOptions.Add (this.checkSetWidth);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.tableClearTablesOptions [this.checkSetWidth]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableClearTablesOptions.Gtk.Table+TableChild
			this.comboWidthUnits = global::Gtk.ComboBox.NewText ();
			this.comboWidthUnits.AppendText (global::Mono.Unix.Catalog.GetString ("%"));
			this.comboWidthUnits.AppendText (global::Mono.Unix.Catalog.GetString ("px"));
			this.comboWidthUnits.AppendText (global::Mono.Unix.Catalog.GetString ("pc"));
			this.comboWidthUnits.AppendText (global::Mono.Unix.Catalog.GetString ("em"));
			this.comboWidthUnits.AppendText (global::Mono.Unix.Catalog.GetString ("ex"));
			this.comboWidthUnits.AppendText (global::Mono.Unix.Catalog.GetString ("in"));
			this.comboWidthUnits.AppendText (global::Mono.Unix.Catalog.GetString ("pt"));
			this.comboWidthUnits.AppendText (global::Mono.Unix.Catalog.GetString ("cm"));
			this.comboWidthUnits.AppendText (global::Mono.Unix.Catalog.GetString ("mm"));
			this.comboWidthUnits.Name = "comboWidthUnits";
			this.comboWidthUnits.Active = 0;
			this.tableClearTablesOptions.Add (this.comboWidthUnits);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.tableClearTablesOptions [this.comboWidthUnits]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.LeftAttach = ((uint)(2));
			w6.RightAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableClearTablesOptions.Gtk.Table+TableChild
			this.entryTableClass = new global::Gtk.Entry ();
			this.entryTableClass.TooltipMarkup = "CSS class for cleaned table";
			this.entryTableClass.CanFocus = true;
			this.entryTableClass.Name = "entryTableClass";
			this.entryTableClass.Text = global::Mono.Unix.Catalog.GetString ("data");
			this.entryTableClass.IsEditable = true;
			this.entryTableClass.WidthChars = 12;
			this.entryTableClass.InvisibleChar = '●';
			this.tableClearTablesOptions.Add (this.entryTableClass);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.tableClearTablesOptions [this.entryTableClass]));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(3));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableClearTablesOptions.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 1F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("CSS class:");
			this.tableClearTablesOptions.Add (this.label1);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.tableClearTablesOptions [this.label1]));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableClearTablesOptions.Gtk.Table+TableChild
			this.spinTableWidth = new global::Gtk.SpinButton (0, 10000, 1);
			this.spinTableWidth.TooltipMarkup = "Width in % for cleaned table";
			this.spinTableWidth.CanFocus = true;
			this.spinTableWidth.Name = "spinTableWidth";
			this.spinTableWidth.Adjustment.PageIncrement = 10;
			this.spinTableWidth.ClimbRate = 10;
			this.spinTableWidth.Numeric = true;
			this.spinTableWidth.SnapToTicks = true;
			this.spinTableWidth.Value = 100;
			this.tableClearTablesOptions.Add (this.spinTableWidth);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tableClearTablesOptions [this.spinTableWidth]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			this.alignment2.Add (this.tableClearTablesOptions);
			this.table1.Add (this.alignment2);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment2]));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox4.Add (this.table1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.table1]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.vbox1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
			w13.Position = 0;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			w1.SetUiManager (UIManager);
			this.Hide ();
			this.actionProcess.Activated += new global::System.EventHandler (this.OnActionProcessActivated);
			this.toggleAutoCopy.Toggled += new global::System.EventHandler (this.OnToggleAutoCopyToggled);
		}
	}
}
